<a href="https://colab.research.google.com/github/muhammed-shamil/Classification/blob/main/imageclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn import svm
import os
from skimage.transform import resize  #to resize the image
from skimage.io import imread
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
os.listdir('/content/drive/MyDrive/data science /Machine Learning /svm/test')

['dogs', 'cats']

In [ ]:
len(os.listdir('/content/drive/MyDrive/data science /Machine Learning /svm/test'))

2

In [ ]:
len(os.listdir('/content/drive/MyDrive/data science /Machine Learning /svm/test/cats'))

70

In [ ]:
len(os.path.join('/content/drive/MyDrive/data science /Machine Learning /svm/test','cats'))

68

In [ ]:
flat_data_array = []
target_arr = []
categories = ['cats','dogs']
datadir = '/content/drive/MyDrive/data science /Machine Learning /svm/test'

In [ ]:
for i in categories:
  print('Loading.........category :',i)
  path = os.path.join(datadir,i)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    img_resized = resize(img_array,(150,150,3))
    flat_data_array.append(img_resized.flatten())
    target_arr.append(categories.index(i))
  print('loaded category :',i)

Loading.........category : cats
loaded category : cats
Loading.........category : dogs
loaded category : dogs


In [ ]:
flat_data = np.array(flat_data_array)
target = np.array(target_arr)

df = pd.DataFrame(flat_data)

In [ ]:
df.head()

0         1         2         3         4         5         6      \
0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
1  0.941176  0.941176  0.941176  0.941176  0.941176  0.941176  0.941176   
2  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
3  0.066459  0.050772  0.046851  0.066493  0.050807  0.046885  0.066656   
4  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157   

      7         8         9      ...     67490     67491     67492     67493  \
0  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
1  0.941176  0.941176  0.941176  ...  0.984355  0.956754  0.970721  0.983632   
2  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000   
3  0.050969  0.047048  0.066667  ...  0.047212  0.106876  0.045109  0.042669   
4  0.992157  0.992157  0.992157  ...  0.980119  0.973224  0.973224  0.973224   

      67494     67495     67496     67497     67498     67499  
0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
1  0.951765  0.967450  0.979216  0.951643  0.967330  0.979094  
2  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  
3  0.138280  0.038187  0.038115  0.188594  0.059359  0.061700  
4  0.972549  0.972549  0.972549  0.972549  0.972549  0.972549  

[5 rows x 67500 columns]

In [ ]:
df.shape

(140, 67500)

In [ ]:
df['target'] = target

In [ ]:
df

0         1         2         3         4         5         6  \
0    1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
1    0.941176  0.941176  0.941176  0.941176  0.941176  0.941176  0.941176   
2    1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
3    0.066459  0.050772  0.046851  0.066493  0.050807  0.046885  0.066656   
4    0.992157  0.992157  0.992157  0.992157  0.992157  0.992157  0.992157   
..        ...       ...       ...       ...       ...       ...       ...   
135  0.108179  0.126440  0.117472  0.131021  0.136840  0.130897  0.142595   
136  0.255179  0.317164  0.207298  0.246564  0.316602  0.213517  0.225567   
137  0.145098  0.109804  0.074510  0.145098  0.109804  0.074510  0.145098   
138  0.571466  0.543065  0.502978  0.545882  0.532140  0.505298  0.516727   
139  0.793502  0.671443  0.543091  0.780656  0.628852  0.474770  0.767930   

            7         8         9  ...     67491     67492     67493  \
0    1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
1    0.941176  0.941176  0.941176  ...  0.956754  0.970721  0.983632   
2    1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   
3    0.050969  0.047048  0.066667  ...  0.106876  0.045109  0.042669   
4    0.992157  0.992157  0.992157  ...  0.973224  0.973224  0.973224   
..        ...       ...       ...  ...       ...       ...       ...   
135  0.152673  0.141076  0.157799  ...  0.543393  0.539119  0.525428   
136  0.299391  0.216565  0.212490  ...  0.575063  0.289463  0.277393   
137  0.109804  0.074510  0.145101  ...  0.407967  0.326716  0.303603   
138  0.514006  0.494402  0.490304  ...  0.543187  0.543451  0.548504   
139  0.608017  0.447716  0.790871  ...  0.797953  0.672070  0.497984   

        67494     67495     67496     67497     67498     67499  target  
0    1.000000  1.000000  1.000000  1.000000  1.000000  1.000000       0  
1    0.951765  0.967450  0.979216  0.951643  0.967330  0.979094       0  
2    1.000000  1.000000  1.000000  1.000000  1.000000  1.000000       0  
3    0.138280  0.038187  0.038115  0.188594  0.059359  0.061700       0  
4    0.972549  0.972549  0.972549  0.972549  0.972549  0.972549       0  
..        ...       ...       ...       ...       ...       ...     ...  
135  0.533469  0.527124  0.525000  0.545633  0.538932  0.538797       1  
136  0.666403  0.348591  0.297203  0.712691  0.388277  0.316823       1  
137  0.433181  0.354410  0.320646  0.448993  0.370615  0.335295       1  
138  0.556060  0.558443  0.564019  0.518275  0.542879  0.544279       1  
139  0.803082  0.681208  0.508537  0.803690  0.678609  0.505929       1  

[140 rows x 67501 columns]

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20,random_state=0)

In [ ]:
clf = svm.SVC()

clf.fit(xtrain,ytrain)

SVC()

In [ ]:
y_pred =clf.predict(xtest)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,f1_score,recall_score


In [ ]:
accuracy_score(y_pred,ytest)

0.4642857142857143

In [ ]:
confusion_matrix(y_pred,ytest)

array([[ 4,  5],
       [10,  9]])

In [ ]:
precision_score(y_pred,ytest)

0.6428571428571429

In [ ]:
f1_score(y_pred,ytest)

0.5454545454545454

In [ ]:
recall_score(y_pred,ytest)

0.47368421052631576

In [ ]:
path = '/content/drive/MyDrive/data science /Machine Learning /svm/test/cats/cat_1.jpg'
img = imread(path)
img = resize(img,(150,150,3)).flatten().reshape(1, -1)
clf.predict(img)

array([0])

In [ ]:
path = '/content/drive/MyDrive/data science /Machine Learning /svm/test/dogs/dog_142.jpg'
img = imread(path)
img = resize(img,(150,150,3)).flatten().reshape(1, -1)
clf.predict(img)

array([1])